name: build-functions

on:
  push:
    branches:
      - main

jobs:
  hello-world-node:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./functions/hello-world/Dockerfile
          context: ./functions/hello-world
          tags: ghcr.io/${{ github.repository_owner }}/serverless-hello-world:latest

  hello-world-bash:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./functions/hello-bash/Dockerfile
          context: ./functions/hello-bash
          tags: ghcr.io/${{ github.repository_owner }}/serverless-hello-bash:latest
